Update git articles
infinum/qa-handbook pull request #157
Opened 2023-03-29 09:41 UTC by dino-vinkovic

Related to task https://app.productive.io/1-infinum/tasks/3437736

Using Git articles were just slightly updated.
Code management article added. The idea is to briefly cover hosting services and focus more on those, rather than to have both e.g. git and GitHub info in once place. Those are not the same thing and should be separated.

2023-04-04 12:01 UTC, igor-pekovic requested changes

2023-04-04 12:01 UTC, igor-pekovic commented on Tools/Version Control Systems/Code management.md
> +A version controls system is used for managing your source code. One of those systems is `git`.
`controls` should be in singular - `control`?

2023-04-04 12:01 UTC, igor-pekovic commented on Tools/Version Control Systems/Using Git - Basics.md
> +Afterwards, you can make the changes to your files, stage them, commit and push to the remote repository.
Should `[Using Git - Advanced]` be linked to the beta subdomain?

2023-04-05 07:34 UTC, dino-vinkovic commented on Tools/Version Control Systems/Using Git - Basics.md
> +Afterwards, you can make the changes to your files, stage them, commit and push to the remote repository.
Ups. Good catch.

2023-04-05 08:52 UTC, igor-pekovic approved these changes

2023-04-27 13:20 UTC, merged